### ISSUE TITLE
Discord.py discontinued

### ISSUE THREAD

**Issue by hasanlatch007** [UrLab/UrBot#1]
https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1#file-the_future_of_dpy-md

Discord.py is discontinued time to switch to Discord.js :)

**Comment by Minigrim0** [comment]
## Alternatives:
* [Pycord](https://github.com/Pycord-Development/pycord)
* [hikari](https://github.com/hikari-py/hikari)
* [Nextcord](https://github.com/nextcord/nextcord)
* [Enhanced-dpy](https://github.com/iDevision/enhanced-discord.py)

No js for me :upside_down_face:
